# code: language=ansible

- name: Install Mac Developer Tools
  hosts: all

  vars_files:
    - vars.yaml

  tasks:
    - name: Copy home directory files
      ansible.builtin.copy:
        src: home/
        dest: "{{ ansible_env.HOME }}"
        mode: "0644"

    - name: Install defaults
      ansible.builtin.import_tasks: tasks/install-defaults.yaml
      tags: [defaults]

    - name: Install Homebrew
      ansible.builtin.import_tasks: tasks/install-homebrew.yaml
      tags: [homebrew]

    - name: Install Bash
      ansible.builtin.import_tasks: tasks/install-bash.yaml
      tags: [bash]

    - name: Install Homebrew formulas
      ansible.builtin.import_tasks: tasks/install-homebrew-formulas.yaml
      tags: [homebrew]

    - name: Install Homebrew casks
      ansible.builtin.import_tasks: tasks/install-homebrew-casks.yaml
      tags: [homebrew]

    - name: Install SF Mono font
      ansible.builtin.import_tasks: tasks/install-sf-mono.yaml
      tags: [fonts]

    - name: Install VS Code
      ansible.builtin.import_tasks: tasks/install-vs-code.yaml
      tags: [editors]

    - name: Install Docker
      ansible.builtin.import_tasks: tasks/install-docker.yaml
      tags: [containers]

    - name: Install Git
      ansible.builtin.import_tasks: tasks/install-git.yaml
      tags: [version-control]

    - name: Install Python
      ansible.builtin.import_tasks: tasks/install-python.yaml
      tags: [languages]

    - name: Install App Store apps
      ansible.builtin.import_tasks: tasks/install-app-store.yaml
      tags: [appstore]
