# code: language=ansible

- name: Install Mac Developer Tools
  hosts: all

  vars_files:
    - vars.yaml

  tasks:
    - name: Copy home directory files
      ansible.builtin.copy:
        src: home/
        dest: "{{ ansible_env.HOME }}"
        mode: "0644"

    - name: Set up file permissions
      ansible.builtin.import_tasks: tasks/file-permissions.yaml
      tags: [permissions]

    - name: Install defaults
      ansible.builtin.import_tasks: tasks/install-defaults.yaml
      tags: [defaults]

    - name: Install Homebrew
      ansible.builtin.import_tasks: tasks/install-homebrew.yaml
      tags: [homebrew]

    - name: Install Bash
      ansible.builtin.import_tasks: tasks/install-bash.yaml
      tags: [bash]

    - name: Install Homebrew formulas
      ansible.builtin.import_tasks: tasks/install-homebrew-formulas.yaml
      tags: [homebrew]

    - name: Install Homebrew casks
      ansible.builtin.import_tasks: tasks/install-homebrew-casks.yaml
      tags: [homebrew]

    - name: Install Git
      ansible.builtin.import_tasks: tasks/install-git.yaml
      tags: [version-control]

    - name: Install Alacritty
      ansible.builtin.import_tasks: tasks/install-alacritty.yaml
      tags: [terminals]

    - name: Install fzf
      ansible.builtin.import_tasks: tasks/install-fzf.yaml
      tags: [tools]

    - name: Install asdf
      ansible.builtin.import_tasks: tasks/install-asdf.yaml
      tags: [tool-version-manager]

    - name: Install asdf tools
      ansible.builtin.import_tasks: tasks/install-asdf-tools.yaml
      tags: [tool-version-manager]

    - name: Install Docker
      ansible.builtin.import_tasks: tasks/install-docker.yaml
      tags: [containers]

    - name: Install neovim
      ansible.builtin.import_tasks: tasks/install-nvim.yaml
      tags: [editors]

    - name: Install VS Code
      ansible.builtin.import_tasks: tasks/install-vs-code.yaml
      tags: [editors]

    - name: Install SF Mono font
      ansible.builtin.import_tasks: tasks/install-sf-mono.yaml
      tags: [fonts]

    - name: Install Google Cloud SDK
      ansible.builtin.import_tasks: tasks/install-gcloud-cli.yaml
      when: install_gcloud
      tags: [fonts]

    - name: Install App Store apps
      ansible.builtin.import_tasks: tasks/install-app-store.yaml
      when: install_mas
      tags: [appstore]
