import = ["~/.config/alacritty/themes/themes/github_dark_colorblind.toml"]

[window]
decorations = "none"
option_as_alt = "Both"

[font]
normal = { family = "SF Mono", style = "Regular" }

[cursor]
style = { blinking = "On", shape = "Block" }
blink_interval = 500
blink_timeout = 0

[keyboard]
bindings = [
  # Move word by word
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left", mods = "Alt", chars = "\u001BB" },
  # Move to beginning/end of line
  { key = "Right", mods = "Super", chars = "\u001BOF" },
  { key = "Left", mods = "Super", chars = "\u001BOH" },
  # Switch between tabs
  { key = "Right", mods = "Alt | Super", action = "SelectNextTab" },
  { key = "Left", mods = "Alt | Super", action = "SelectPreviousTab" },
]
