# code: language=ansible

- name: Install Rust asdf plugin
  ansible.builtin.shell:
    cmd: . "{{ ansible_env.HOME }}/.asdf/asdf.sh" && asdf plugin add rust https://github.com/code-lever/asdf-rust.git
    executable: "{{ homebrew_path }}/bin/bash"
  register: asdf_plugin_rust
  changed_when: asdf_plugin_rust.rc == 0 and asdf_plugin_rust.stdout != "Plugin named rust already added"

- name: Install Go asdf plugin
  ansible.builtin.shell:
    cmd: . "{{ ansible_env.HOME }}/.asdf/asdf.sh" && asdf plugin add golang https://github.com/asdf-community/asdf-golang.git
    executable: "{{ homebrew_path }}/bin/bash"
  register: asdf_plugin_golang
  changed_when: asdf_plugin_golang.rc == 0 and asdf_plugin_golang.stdout != "Plugin named golang already added"

- name: Install Node.js asdf plugin
  ansible.builtin.shell:
    cmd: . "{{ ansible_env.HOME }}/.asdf/asdf.sh" && asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
    executable: "{{ homebrew_path }}/bin/bash"
  register: asdf_plugin_nodejs
  changed_when: asdf_plugin_nodejs.rc == 0 and asdf_plugin_nodejs.stdout != "Plugin named nodejs already added"

- name: Install latest Rust
  ansible.builtin.shell:
    cmd: . "{{ ansible_env.HOME }}/.asdf/asdf.sh" && asdf install rust latest
    executable: "{{ homebrew_path }}/bin/bash"
  register: asdf_rust_latest
  changed_when: asdf_rust_latest.rc == 0 and "is already installed" not in asdf_rust_latest.stdout

- name: Install latest Go
  ansible.builtin.shell:
    cmd: . "{{ ansible_env.HOME }}/.asdf/asdf.sh" && asdf install golang latest
    executable: "{{ homebrew_path }}/bin/bash"
  register: asdf_golang_latest
  changed_when: asdf_golang_latest.rc == 0 and "is already installed" not in asdf_golang_latest.stdout

- name: Install latest Node.js
  ansible.builtin.shell:
    cmd: . "{{ ansible_env.HOME }}/.asdf/asdf.sh" && asdf install nodejs latest
    executable: "{{ homebrew_path }}/bin/bash"
  register: asdf_nodejs_latest
  changed_when: asdf_nodejs_latest.rc == 0 and "is already installed" not in asdf_nodejs_latest.stdout

- name: Enable corepack and re-shim Node.js
  ansible.builtin.shell:
    cmd: . "{{ ansible_env.HOME }}/.asdf/asdf.sh" && corepack enable && asdf reshim nodejs
    executable: "{{ homebrew_path }}/bin/bash"
  changed_when: false

- name: Set global Rust version
  ansible.builtin.shell:
    cmd: . "{{ ansible_env.HOME }}/.asdf/asdf.sh" && asdf global rust latest
    executable: "{{ homebrew_path }}/bin/bash"
  register: asdf_rust_global
  changed_when: false

- name: Set global Go version
  ansible.builtin.shell:
    cmd: . "{{ ansible_env.HOME }}/.asdf/asdf.sh" && asdf global golang latest
    executable: "{{ homebrew_path }}/bin/bash"
  register: asdf_golang_global
  changed_when: false

- name: Set global Node.js version
  ansible.builtin.shell:
    cmd: . "{{ ansible_env.HOME }}/.asdf/asdf.sh" && asdf global nodejs latest
    executable: "{{ homebrew_path }}/bin/bash"
  register: asdf_nodejs_global
  changed_when: false
