# code: language=ansible

- name: Check if gcloud is available
  ansible.builtin.command: command -v gcloud
  register: gcloud_exists
  changed_when: false
  failed_when: gcloud_exists.rc > 1

- name: Add gcloud to .bash_profile
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.bash_profile"
    append_newline: true
    prepend_newline: true
    marker: "# {mark} gcloud"
    block: |
      if [ -f "$(brew --prefix)/share/google-cloud-sdk/path.bash.inc" ]; then . "$(brew --prefix)/share/google-cloud-sdk/path.bash.inc"; fi
  when: gcloud_exists.rc == 0

- name: Update gcloud
  ansible.builtin.command: gcloud components update --quiet
  register: gcloud_update
  changed_when: gcloud_update.rc == 0 and "All components are up to date." not in gcloud_update.stderr
  when: gcloud_exists.rc == 0
