# code: language=ansible

- name: Check if Docker is installed
  ansible.builtin.stat:
    path: "/Applications/Docker.app"
  register: docker_exists

- name: Create temporary directory for Docker files
  ansible.builtin.tempfile:
    state: directory
  register: docker_mktempd
  when: not docker_exists.stat.exists

- name: Download Docker
  ansible.builtin.get_url:
    url: "https://desktop.docker.com/mac/main/{{ docker_arch }}/Docker.dmg"
    dest: "{{ docker_mktempd.path }}/Docker.dmg"
    mode: "0644"
  when: not docker_exists.stat.exists

- name: Mount disk image
  ansible.builtin.command: hdiutil attach "{{ docker_mktempd.path }}/Docker.dmg" -nobrowse -mountpoint "{{ docker_mktempd.path }}/Docker"
  register: docker_mount
  changed_when: docker_mount.rc != 0
  when: not docker_exists.stat.exists

- name: Install Docker
  ansible.builtin.command: "{{ docker_mktempd.path }}/Docker/Docker.app/Contents/MacOS/install --accept-license"
  become: true
  register: docker_install
  changed_when: docker_install.rc != 0
  when: not docker_exists.stat.exists

- name: Unmount disk image
  ansible.builtin.command: hdiutil detach "{{ docker_mktempd.path }}/Docker"
  register: docker_unmount
  changed_when: docker_unmount.rc != 0
  when: not docker_exists.stat.exists

- name: Remove temporary directory
  ansible.builtin.file:
    path: "{{ docker_mktempd.path }}"
    state: absent
  when: docker_mktempd.path is defined
