# code: language=ansible

- name: Check if cargo is available
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.cargo/bin/cargo"
  register: cargo_exists

- name: Create temporary directory for rustup
  ansible.builtin.tempfile:
    state: directory
  register: rustup_mktempd
  when: not cargo_exists.stat.exists

- name: Download rustup
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: "{{ rustup_mktempd.path }}"
    mode: "0755"
  register: rustup_download
  when: rustup_mktempd.path is defined

- name: Install Rust
  ansible.builtin.command: "{{ rustup_download.dest }} -y --quiet --no-modify-path"
  register: rustup_install
  changed_when: rustup_install.rc == 0
  when: rustup_download.dest is defined

- name: Delete temporary directory for rustup
  ansible.builtin.file:
    path: "{{ rustup_mktempd.path }}"
    state: absent
  when: rustup_mktempd.path is defined

- name: Add cargo to .bash_profile
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.bash_profile"
    append_newline: true
    prepend_newline: true
    marker: "# {mark} Load Rust"
    block: |
      if [ -f "$HOME/.cargo/env" ]; then
        . "$HOME/.cargo/env"
      fi
