# code: language=ansible

- name: Check if SF Mono is installed
  ansible.builtin.stat:
    path: /Library/Fonts/SF-Mono-Regular.otf
  register: sfmono_exists

- name: Create temporary directory for SF Mono files
  ansible.builtin.tempfile:
    state: directory
  register: sfmono_mktempd
  when: not sfmono_exists.stat.exists

- name: Download SF Mono Fonts
  ansible.builtin.get_url:
    url: https://devimages-cdn.apple.com/design/resources/download/SF-Mono.dmg
    dest: "{{ sfmono_mktempd.path }}/SF-Mono.dmg"
    mode: "0644"
  when: not sfmono_exists.stat.exists

- name: Mount disk image
  ansible.builtin.command: hdiutil attach "{{ sfmono_mktempd.path }}/SF-Mono.dmg" -nobrowse -mountpoint "{{ sfmono_mktempd.path }}/SF-Mono"
  register: sfmono_mount
  changed_when: sfmono_mount.rc != 0
  when: not sfmono_exists.stat.exists

- name: Install SF Mono Fonts
  ansible.builtin.command: installer -pkg "{{ sfmono_mktempd.path }}/SF-Mono/SF Mono Fonts.pkg" -target /
  become: true
  register: sfmono_install
  changed_when: sfmono_install.rc != 0
  when: not sfmono_exists.stat.exists

- name: Unmount disk image
  ansible.builtin.command: hdiutil detach "{{ sfmono_mktempd.path }}/SF-Mono"
  register: sfmono_unmount
  changed_when: sfmono_unmount.rc != 0
  when: not sfmono_exists.stat.exists

- name: Remove temporary directory
  ansible.builtin.file:
    path: "{{ sfmono_mktempd.path }}"
    state: absent
  when: sfmono_mktempd.path is defined
