# Install .dmg

- name: Check if Docker is installed
  ansible.builtin.shell: test -e '/Applications/Docker.app'
  register: docker_exists
  ignore_errors: true

- name: Create temporary file
  command: mktemp
  register: mktempf
  when: docker_exists.rc != 0

- name: Download Docker
  command: curl -sLo {{ mktempf.stdout }} 'https://desktop.docker.com/mac/main/arm64/Docker.dmg'
  when: docker_exists.rc != 0

- name: Create temporary directory
  command: mktemp -d
  register: mktempd
  when: docker_exists.rc != 0

- name: Mount disk image
  command: hdiutil attach {{ mktempf.stdout }} -nobrowse -mountpoint {{ mktempd.stdout }}
  when: docker_exists.rc != 0

- name: Install Docker
  command: "{{ mktempd.stdout }}/Docker.app/Contents/MacOS/install --accept-license"
  vars:
    ansible_become: true
    ansible_become_password: "{{ password }}"
  when: docker_exists.rc != 0

- name: Unmount disk image
  command: hdiutil detach -force {{ mktempd.stdout }}
  when: docker_exists.rc != 0

- name: Remove temporary directory
  command: rm -rf {{ mktempd.stdout }}
  when: docker_exists.rc != 0

- name: Remove temporary file
  command: rm -f {{ mktempf.stdout }}
  when: docker_exists.rc != 0
