name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - macos-latest
          - macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run RUNME.sh
        run: ./RUNME.sh
